#!/bin/sh

BANNED_LIST=banned_addresses.txt

ADDRESS=$1

FOUND=`iptables -L BLACKLIST -n | awk '{print \$4}' | grep -F $ADDRESS`

if [ -z "$FOUND" ]
then
  echo $ADDRESS will be banned
  echo $ADDRESS >> $BANNED_LIST
  iptables -I BLACKLIST -s $ADDRESS -j DROP
  iptables-save > /etc/iptables/rules.v4
else
  echo $ADDRESS is already banned
fi
